"""
orphaned_asset_scanner.py - MCNA Tenant Intel

Inventories orphaned M365 groups, Teams, distribution lists, user accounts,
SharePoint sites, and Planner plans in orphaned groups.
Produces a prioritized cleanup queue for Dave's review. Read-only throughout.

Run on demand (not scheduled). No email delivery.

Reads credentials from: C:/Users/dlafferty.MCNA/mcna-tenantintel.env
Auth (delegated): Admin account, MSAL device code flow, token cached locally.
Auth (app):       Certificate from Windows cert store (CERT_THUMBPRINT in .env).
                  Used only for Planner (Tasks.Read.All application permission).
"""

import sys
sys.dont_write_bytecode = True

import csv
import datetime
import io
import pathlib

import msal
import requests
from cryptography.hazmat.primitives.serialization import pkcs12
from cryptography.hazmat.primitives import serialization as crypto_serialization


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

ENV_PATH = r"C:/Users/dlafferty.MCNA/mcna-tenantintel.env"

PROJECT_ROOT = pathlib.Path(__file__).parent
REPORTS_DIR = PROJECT_ROOT / "reports" / "orphaned-assets"
ACTIVITY_LOG = PROJECT_ROOT / "activity-log.md"

ADMIN_TOKEN_CACHE = pathlib.Path(r"C:/Users/dlafferty.MCNA/.msal_token_cache_admin.json")

GRAPH_V1 = "https://graph.microsoft.com/v1.0"

ADMIN_SCOPES = [
    "Directory.Read.All",
    "AuditLog.Read.All",
    "Reports.Read.All",
    "Sites.Read.All",
    "User.Read",
]

# Used for client credentials flow (Tasks.Read.All application permission)
PLANNER_SCOPES = ["https://graph.microsoft.com/.default"]

HIGH = "High"
MEDIUM = "Medium"
LOW = "Low"

SEVERITY_ORDER = {HIGH: 0, MEDIUM: 1, LOW: 2, "Clean": 3}

# Groups created longer ago than this with zero activity are flagged
GROUP_INACTIVITY_DAYS = 180

# Users enabled but not signed in for this long are flagged
USER_STALE_DAYS = 365

# Users created longer than this ago and never signed in are flagged
USER_NEVER_SIGNIN_DAYS = 90


# ---------------------------------------------------------------------------
# Load .env
# ---------------------------------------------------------------------------

def load_env(path):
    env = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    return env


# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------

def get_token(tenant_id, client_id, scopes, cache_path, login_hint=None):
    cache = msal.SerializableTokenCache()
    if cache_path.exists():
        cache.deserialize(cache_path.read_text())

    app = msal.PublicClientApplication(
        client_id=client_id,
        authority=f"https://login.microsoftonline.com/{tenant_id}",
        token_cache=cache,
    )

    accounts = app.get_accounts(username=login_hint)
    result = None
    if accounts:
        result = app.acquire_token_silent(scopes, account=accounts[0])

    if not result:
        flow = app.initiate_device_flow(scopes=scopes)
        if "user_code" not in flow:
            raise RuntimeError(f"Device flow failed: {flow}")
        print("\n" + flow["message"])
        print("Waiting for authentication...\n")
        result = app.acquire_token_by_device_flow(flow)

    if "access_token" not in result:
        raise RuntimeError(f"Auth failed: {result.get('error_description', result)}")

    if cache.has_state_changed:
        cache_path.write_text(cache.serialize())

    return result["access_token"]


def get_app_token(tenant_id, client_id, thumbprint, pfx_path):
    """
    Authenticate as the application using a PFX certificate file.
    PFX must have no password (as generated by this project).
    Returns an access token scoped to Tasks.Read.All (via .default).
    """
    pfx_bytes = pathlib.Path(pfx_path).read_bytes()
    try:
        private_key, _, _ = pkcs12.load_key_and_certificates(pfx_bytes, None)
    except Exception:
        private_key, _, _ = pkcs12.load_key_and_certificates(pfx_bytes, b"")

    private_key_pem = private_key.private_bytes(
        encoding=crypto_serialization.Encoding.PEM,
        format=crypto_serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=crypto_serialization.NoEncryption(),
    )

    app = msal.ConfidentialClientApplication(
        client_id,
        authority=f"https://login.microsoftonline.com/{tenant_id}",
        client_credential={"thumbprint": thumbprint, "private_key": private_key_pem.decode()},
    )
    token_result = app.acquire_token_for_client(scopes=PLANNER_SCOPES)
    if "access_token" not in token_result:
        raise RuntimeError(f"App token failed: {token_result.get('error_description', token_result)}")
    return token_result["access_token"]


# ---------------------------------------------------------------------------
# Graph helpers
# ---------------------------------------------------------------------------

def graph_get(token, url, params=None, headers_extra=None):
    headers = {"Authorization": f"Bearer {token}"}
    if headers_extra:
        headers.update(headers_extra)
    resp = requests.get(url, headers=headers, params=params)
    if resp.status_code in (401, 403):
        raise RuntimeError(f"Graph auth error {resp.status_code}: {resp.text}")
    resp.raise_for_status()
    return resp


def get_all_pages(token, url, params=None, headers_extra=None):
    items = []
    resp = graph_get(token, url, params, headers_extra)
    data = resp.json()
    items.extend(data.get("value", []))
    while "@odata.nextLink" in data:
        resp = graph_get(token, data["@odata.nextLink"], headers_extra=headers_extra)
        data = resp.json()
        items.extend(data.get("value", []))
    return items


# ---------------------------------------------------------------------------
# Graph queries
# ---------------------------------------------------------------------------

def fetch_groups(token):
    """Fetch all groups with owner expansion."""
    url = f"{GRAPH_V1}/groups"
    params = {
        "$select": (
            "id,displayName,mail,groupTypes,mailEnabled,securityEnabled,"
            "visibility,createdDateTime,description"
        ),
        "$expand": "owners($select=id,displayName,userPrincipalName,accountEnabled)",
        "$top": 999,
    }
    return get_all_pages(token, url, params)


def fetch_group_member_count(token, group_id):
    """
    Returns member count for a group, or None if throttled/unavailable.
    Uses ConsistencyLevel: eventual for $count support.
    """
    url = f"{GRAPH_V1}/groups/{group_id}/members/$count"
    try:
        resp = graph_get(token, url, headers_extra={"ConsistencyLevel": "eventual"})
        return int(resp.text)
    except Exception:
        return None


def fetch_users(token):
    """Fetch all users with sign-in activity and license info."""
    url = f"{GRAPH_V1}/users"
    params = {
        "$select": (
            "id,displayName,userPrincipalName,accountEnabled,assignedLicenses,"
            "mail,createdDateTime,jobTitle,department,signInActivity"
        ),
        "$top": 999,
    }
    try:
        return get_all_pages(token, url, params)
    except Exception as e:
        # signInActivity may not be available on all tenants/licenses.
        # Fall back without it.
        if "signInActivity" in str(e):
            print("  NOTE: signInActivity not available — retrying without it")
            params["$select"] = (
                "id,displayName,userPrincipalName,accountEnabled,assignedLicenses,"
                "mail,createdDateTime,jobTitle,department"
            )
            return get_all_pages(token, url, params)
        raise


def fetch_planner_plans_for_group(app_token, group_id):
    """
    Returns list of Planner plan dicts for the given group.
    Uses application token (Tasks.Read.All). Returns empty list on any error.
    """
    url = f"{GRAPH_V1}/groups/{group_id}/planner/plans"
    try:
        data = graph_get(app_token, url).json()
        return data.get("value", [])
    except Exception:
        return []


def fetch_sharepoint_sites(token):
    """
    Fetch all SharePoint sites tenant-wide via search=*.
    Returns list of site objects with id, displayName, webUrl, createdDateTime.
    """
    url = f"{GRAPH_V1}/sites"
    params = {
        "search": "*",
        "$select": "id,displayName,name,webUrl,createdDateTime,lastModifiedDateTime",
        "$top": 200,
    }
    try:
        sites = get_all_pages(token, url, params)
        # Filter out the root site (/sites/root) and OneDrive personal sites
        sites = [
            s for s in sites
            if "/personal/" not in (s.get("webUrl") or "").lower()
        ]
        print(f"  {len(sites)} SharePoint sites (excluding personal OneDrive)")
        return sites
    except RuntimeError as e:
        if "403" in str(e) or "401" in str(e):
            raise
        print(f"  NOTE: SharePoint site enumeration failed ({e}) — skipping")
        return []


def fetch_sharepoint_usage_report(token):
    """
    Fetch SharePoint site usage detail (last 180 days).
    Returns dict: site-collection-guid -> {owner_upn, last_activity, storage_bytes, active_files}.
    Returns None if unavailable.

    Microsoft returns a BOM-prefixed CSV with Site URL always empty;
    Site Id (the site-collection GUID) is the only reliable key.
    """
    url = f"{GRAPH_V1}/reports/getSharePointSiteUsageDetail(period='D180')"
    try:
        resp = graph_get(token, url)
        # Decode with utf-8-sig to strip BOM; Site URL is always empty in this report
        text = resp.content.decode("utf-8-sig")
        reader = csv.DictReader(io.StringIO(text))
        usage = {}
        for row in reader:
            site_id = (row.get("Site Id") or "").strip().lower()
            if not site_id:
                continue
            usage[site_id] = {
                "owner_upn": (row.get("Owner Principal Name") or "").strip().lower(),
                "owner_display": (row.get("Owner Display Name") or "").strip(),
                "last_activity": (row.get("Last Activity Date") or "").strip(),
                "storage_bytes": row.get("Storage Used (Byte)", "0").strip(),
                "active_files": row.get("Active File Count", "0").strip(),
                "is_deleted": (row.get("Is Deleted") or "").strip().lower() == "true",
            }
        print(f"  {len(usage)} sites in SharePoint usage report")
        return usage
    except Exception as e:
        print(f"  NOTE: SharePoint usage report unavailable ({e}) — skipping activity checks")
        return None


def fetch_group_activity_report(token):
    """
    Fetch M365 group activity report (last 180 days).
    Returns dict: groupId -> lastActivityDate (str or None).
    Returns None if endpoint unavailable.
    """
    url = f"{GRAPH_V1}/reports/getOffice365GroupsActivityDetail(period='D180')"
    try:
        resp = graph_get(token, url)
        # Response is CSV text
        reader = csv.DictReader(io.StringIO(resp.text))
        activity = {}
        for row in reader:
            group_id = row.get("Group Id") or row.get("group Id") or ""
            last_activity = (
                row.get("Last Activity Date")
                or row.get("lastActivityDate")
                or ""
            ).strip()
            if group_id:
                activity[group_id] = last_activity or None
        print(f"  {len(activity)} groups in activity report")
        return activity
    except Exception as e:
        print(f"  NOTE: Group activity report unavailable ({e}) — skipping inactivity checks")
        return None


# ---------------------------------------------------------------------------
# Active user set (HR roster proxy)
# ---------------------------------------------------------------------------

def build_active_user_set(users):
    """
    Returns set of userPrincipalName (lowercased) for accounts considered active:
    accountEnabled=True. Sign-in recency is a separate check; this set is for
    owner-correlation (can an owner still log in at all?).
    """
    return {
        u["userPrincipalName"].lower()
        for u in users
        if u.get("accountEnabled") and u.get("userPrincipalName")
    }


# ---------------------------------------------------------------------------
# Group classification helpers
# ---------------------------------------------------------------------------

def is_m365_group(group):
    return "Unified" in (group.get("groupTypes") or [])


def is_distribution_or_mail_security(group):
    return (
        group.get("mailEnabled")
        and not is_m365_group(group)
    )


def owners_all_disabled(group):
    owners = group.get("owners") or []
    if not owners:
        return False
    return all(o.get("accountEnabled") is False for o in owners)


def owner_count_disabled(group):
    owners = group.get("owners") or []
    return sum(1 for o in owners if o.get("accountEnabled") is False)


# ---------------------------------------------------------------------------
# Group analysis
# ---------------------------------------------------------------------------

def analyze_group(group, activity_map, now, token):
    findings = []
    owners = group.get("owners") or []
    created_str = (group.get("createdDateTime") or "")[:10]
    group_id = group["id"]

    try:
        created_dt = datetime.datetime.strptime(created_str, "%Y-%m-%d")
        age_days = (now - created_dt).days
    except Exception:
        age_days = None

    if is_m365_group(group):
        # No owners
        if not owners:
            findings.append((HIGH, "No owners assigned"))
        elif owners_all_disabled(group):
            findings.append((HIGH, "All owners have disabled accounts"))
        elif owner_count_disabled(group) > 0 and len(owners) == 1:
            findings.append((MEDIUM, "Single owner account is disabled"))

        # Activity check
        if activity_map is not None and age_days is not None and age_days > GROUP_INACTIVITY_DAYS:
            last_activity = activity_map.get(group_id)
            if not last_activity:
                findings.append((MEDIUM, f"No activity recorded in last {GROUP_INACTIVITY_DAYS} days (group age: {age_days}d)"))

        # Empty group (only check groups with other findings to limit API calls)
        if findings:
            count = fetch_group_member_count(token, group_id)
            if count is not None and count == 0:
                findings.append((MEDIUM, "No members"))

    elif is_distribution_or_mail_security(group):
        if not owners:
            findings.append((HIGH, "No owners assigned"))
        elif owners_all_disabled(group):
            findings.append((HIGH, "All owners have disabled accounts"))

        if age_days is not None and age_days > 365 and not findings:
            findings.append((LOW, f"Group age {age_days}d — verify still needed"))

    return findings


# ---------------------------------------------------------------------------
# User analysis
# ---------------------------------------------------------------------------

def parse_dt(dt_str):
    if not dt_str:
        return None
    try:
        return datetime.datetime.fromisoformat(dt_str.replace("Z", "+00:00")).replace(tzinfo=None)
    except Exception:
        return None


def analyze_user(user, now):
    findings = []
    account_enabled = user.get("accountEnabled", True)
    licenses = user.get("assignedLicenses") or []
    mail = user.get("mail") or ""
    sign_in_activity = user.get("signInActivity") or {}
    last_signin_str = sign_in_activity.get("lastSignInDateTime") or ""
    created_str = (user.get("createdDateTime") or "")[:19]

    last_signin = parse_dt(last_signin_str)
    created = parse_dt(created_str)
    age_days = (now - created).days if created else None

    if not account_enabled:
        if licenses:
            findings.append((HIGH, f"Account disabled but has {len(licenses)} license(s) assigned — wasted spend"))
        if mail:
            findings.append((MEDIUM, "Account disabled with mail address — possible orphaned mailbox"))
    else:
        # Enabled account checks
        if last_signin is not None:
            days_since = (now - last_signin).days
            if days_since >= USER_STALE_DAYS:
                findings.append((MEDIUM, f"Enabled account, no sign-in in {days_since} days"))
        elif last_signin_str == "" and age_days is not None and age_days > USER_NEVER_SIGNIN_DAYS:
            findings.append((LOW, f"Enabled account created {age_days}d ago, never signed in"))

    return findings


# ---------------------------------------------------------------------------
# SharePoint site analysis
# ---------------------------------------------------------------------------

# Sites inactive longer than this (and old enough) are flagged
SP_INACTIVITY_DAYS = 180

# Minimum site age before we flag for inactivity (avoid flagging new empty sites)
SP_MIN_AGE_DAYS = 90


def _site_collection_guid(site):
    """
    Extract the site-collection GUID from a Graph site id.
    Graph site ids are 'hostname,site-collection-guid,web-guid'.
    Returns lowercased GUID string, or empty string if unparseable.
    """
    raw = site.get("id") or ""
    parts = raw.split(",")
    if len(parts) == 3:
        return parts[1].lower()
    return raw.lower()


def analyze_sharepoint_site(site, usage_map, active_user_upns, now):
    """
    Returns (usage_record, findings) for a site.
    usage_record may be None if site has no activity data.
    active_user_upns: set of lowercased UPNs for enabled Entra accounts.

    Lookup key: site-collection GUID (middle segment of Graph site id),
    matched against Site Id from the usage report.

    Group-connected sites (Teams) report their backing group email as owner;
    these are skipped for owner-orphan checks since the M365 groups section
    already covers them.
    """
    findings = []
    site_guid = _site_collection_guid(site)
    created_str = (site.get("createdDateTime") or "")[:10]

    try:
        created_dt = datetime.datetime.strptime(created_str, "%Y-%m-%d")
        age_days = (now - created_dt).days
    except Exception:
        age_days = None

    usage = (usage_map or {}).get(site_guid) if site_guid else None

    # Skip sites already marked deleted in the report
    if usage and usage.get("is_deleted"):
        return usage, []

    owner_upn = (usage.get("owner_upn") or "") if usage else ""
    last_activity = (usage.get("last_activity") or "") if usage else ""

    # Owner check — skip group-backed sites (owner is a group email, not a user UPN).
    # Group-connected sites use @mcna.onmicrosoft.com as the owner; those are
    # covered by the M365 groups section.
    if owner_upn and not owner_upn.endswith("@mcna.onmicrosoft.com"):
        if owner_upn not in active_user_upns:
            findings.append((HIGH, f"Site owner '{owner_upn}' not found in active Entra accounts (disabled or departed)"))

    # Inactivity check
    if usage_map is not None:
        if usage is None:
            # Site not in activity report → zero activity in last 180 days
            if age_days is not None and age_days > SP_MIN_AGE_DAYS:
                findings.append((MEDIUM, f"No activity in last {SP_INACTIVITY_DAYS} days (site age: {age_days}d)"))
        elif last_activity:
            try:
                last_dt = datetime.datetime.strptime(last_activity, "%Y-%m-%d")
                inactive_days = (now - last_dt).days
                if inactive_days >= SP_INACTIVITY_DAYS:
                    findings.append((MEDIUM, f"Last activity {inactive_days} days ago ({last_activity})"))
            except Exception:
                pass
        elif usage is not None and not last_activity:
            # In report but no last activity date → no activity recorded
            if age_days is not None and age_days > SP_MIN_AGE_DAYS:
                findings.append((MEDIUM, f"In activity report but no activity date recorded (site age: {age_days}d)"))

    return usage, findings


# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------

def owner_str(group):
    owners = group.get("owners") or []
    if not owners:
        return "NONE"
    parts = []
    for o in owners:
        upn = o.get("userPrincipalName") or o.get("displayName", "?")
        enabled = o.get("accountEnabled")
        status = "" if enabled else " [DISABLED]"
        parts.append(f"{upn}{status}")
    return ", ".join(parts)


def user_owner_str(user):
    return user.get("userPrincipalName") or user.get("displayName", "?")


def last_activity_str(group_id, activity_map):
    if activity_map is None:
        return "N/A"
    val = activity_map.get(group_id)
    return val or "None recorded"


def max_severity(findings):
    if not findings:
        return "Clean"
    return min(findings, key=lambda f: SEVERITY_ORDER.get(f[0], 99))[0]


# ---------------------------------------------------------------------------
# Output: Markdown
# ---------------------------------------------------------------------------

def build_markdown(
    m365_results, dl_results, user_results, sp_results,
    today_str, now_str, tenant_id,
    activity_available, signin_available,
    sp_available, group_plans,
):
    def count_sev(results, sev):
        return sum(1 for row in results if any(s == sev for s, _ in row[1]))

    def has_findings(row):
        return bool(row[1])

    all_results = (m365_results, dl_results, user_results, sp_results)
    total_flagged = sum(sum(1 for row in r if has_findings(row)) for r in all_results)
    high = sum(count_sev(r, HIGH) for r in all_results)
    medium = sum(count_sev(r, MEDIUM) for r in all_results)
    low = sum(count_sev(r, LOW) for r in all_results)

    lines = [
        f"# Orphaned Asset Scan — {today_str}",
        "",
        f"Generated: {now_str}  ",
        f"Tenant: {tenant_id}  ",
        "",
        "## Summary",
        "",
        f"- M365 Groups / Teams scanned: {len(m365_results)}",
        f"- Distribution / mail-enabled security groups scanned: {len(dl_results)}",
        f"- Users scanned: {len(user_results)}",
        f"- SharePoint sites scanned: {len(sp_results)}" + ("" if sp_available else " (unavailable — Sites.Read.All unavailable)"),
        f"- Assets flagged: {total_flagged} — High: {high} | Medium: {medium} | Low: {low}",
        "",
    ]

    if not activity_available:
        lines += ["**NOTE:** M365 group activity report unavailable — inactivity checks skipped.", ""]
    if not signin_available:
        lines += ["**NOTE:** signInActivity unavailable — user sign-in age checks skipped.", ""]
    if not sp_available:
        lines += ["**NOTE:** SharePoint site enumeration unavailable — SP section skipped.", ""]

    # M365 Groups section
    flagged_m365 = [(g, f) for g, f in m365_results if f]
    if flagged_m365:
        lines += ["## M365 Groups / Teams — Flagged", ""]
        for sev in (HIGH, MEDIUM, LOW):
            section = [(g, f) for g, f in flagged_m365 if any(s == sev for s, _ in f)]
            if not section:
                continue
            lines += [f"### {sev}", ""]
            for group, findings in sorted(section, key=lambda x: x[0].get("displayName", "").lower()):
                name = group.get("displayName", "(unnamed)")
                mail = group.get("mail") or ""
                created = (group.get("createdDateTime") or "")[:10]
                lines += [
                    f"**{name}**" + (f" ({mail})" if mail else ""),
                    f"- Created: {created}",
                    f"- Owners: {owner_str(group)}",
                    f"- Findings:",
                ]
                for s, desc in sorted(findings, key=lambda x: SEVERITY_ORDER.get(x[0], 99)):
                    lines += [f"  - **[{s}]** {desc}"]
                plans = group_plans.get(group["id"], [])
                if plans:
                    lines += [f"- Planner plans: {', '.join(plans)}"]
                lines += [""]

    # DL / mail-enabled security groups section
    flagged_dl = [(g, f) for g, f in dl_results if f]
    if flagged_dl:
        lines += ["## Distribution Groups / Mail-Enabled Security Groups — Flagged", ""]
        for sev in (HIGH, MEDIUM, LOW):
            section = [(g, f) for g, f in flagged_dl if any(s == sev for s, _ in f)]
            if not section:
                continue
            lines += [f"### {sev}", ""]
            for group, findings in sorted(section, key=lambda x: x[0].get("displayName", "").lower()):
                name = group.get("displayName", "(unnamed)")
                mail = group.get("mail") or ""
                created = (group.get("createdDateTime") or "")[:10]
                lines += [
                    f"**{name}**" + (f" ({mail})" if mail else ""),
                    f"- Created: {created}",
                    f"- Owners: {owner_str(group)}",
                    f"- Findings:",
                ]
                for s, desc in sorted(findings, key=lambda x: SEVERITY_ORDER.get(x[0], 99)):
                    lines += [f"  - **[{s}]** {desc}"]
                lines += [""]

    # User accounts section
    flagged_users = [(u, f) for u, f in user_results if f]
    if flagged_users:
        lines += ["## User Accounts — Flagged", ""]
        for sev in (HIGH, MEDIUM, LOW):
            section = [(u, f) for u, f in flagged_users if any(s == sev for s, _ in f)]
            if not section:
                continue
            lines += [f"### {sev}", ""]
            for user, findings in sorted(section, key=lambda x: x[0].get("userPrincipalName", "").lower()):
                upn = user.get("userPrincipalName", "(unknown)")
                name = user.get("displayName", "")
                dept = user.get("department") or ""
                title = user.get("jobTitle") or ""
                created = (user.get("createdDateTime") or "")[:10]
                lines += [
                    f"**{upn}**" + (f" — {name}" if name else ""),
                ]
                if title or dept:
                    lines += [f"- Role: {title}" + (f", {dept}" if dept else "")]
                lines += [
                    f"- Created: {created}",
                    f"- Findings:",
                ]
                for s, desc in sorted(findings, key=lambda x: SEVERITY_ORDER.get(x[0], 99)):
                    lines += [f"  - **[{s}]** {desc}"]
                lines += [""]

    # SharePoint sites section
    flagged_sp = [(s, f, u) for s, f, u in sp_results if f]
    if sp_available:
        lines += ["## SharePoint Sites — Flagged", ""]
        if not flagged_sp:
            lines += [f"No issues found across {len(sp_results)} sites.", ""]
        else:
            for sev in (HIGH, MEDIUM, LOW):
                section = [(s, f, u) for s, f, u in flagged_sp if any(sv == sev for sv, _ in f)]
                if not section:
                    continue
                lines += [f"### {sev}", ""]
                for site, findings, usage in sorted(section, key=lambda x: (x[0].get("displayName") or "").lower()):
                    name = site.get("displayName") or site.get("name") or "(unnamed)"
                    url = site.get("webUrl") or ""
                    created = (site.get("createdDateTime") or "")[:10]
                    owner = (usage or {}).get("owner_upn") or ""
                    last_act = (usage or {}).get("last_activity") or ""
                    lines += [
                        f"**{name}**",
                        f"- URL: {url}",
                        f"- Created: {created}",
                    ]
                    if owner:
                        lines += [f"- Owner (report): {owner}"]
                    if last_act:
                        lines += [f"- Last activity: {last_act}"]
                    lines += ["- Findings:"]
                    for sv, desc in sorted(findings, key=lambda x: SEVERITY_ORDER.get(x[0], 99)):
                        lines += [f"  - **[{sv}]** {desc}"]
                    lines += [""]

    lines += [
        "---",
        f"mcna-tenant-intel orphaned_asset_scanner.py — {now_str}",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Output: CSV
# ---------------------------------------------------------------------------

def build_csv_rows(m365_results, dl_results, user_results, sp_results):
    rows = []

    for group, findings in m365_results:
        if not findings:
            continue
        rows.append({
            "Type": "M365 Group/Team",
            "Display Name": group.get("displayName", ""),
            "ID/Email": group.get("mail") or group.get("id", ""),
            "Owners": owner_str(group),
            "Created": (group.get("createdDateTime") or "")[:10],
            "Last Activity": "",
            "Max Severity": max_severity(findings),
            "Findings": "; ".join(f"[{s}] {d}" for s, d in findings),
            "Recommended Action": "Review and reassign owner or delete group",
        })

    for group, findings in dl_results:
        if not findings:
            continue
        rows.append({
            "Type": "Distribution Group",
            "Display Name": group.get("displayName", ""),
            "ID/Email": group.get("mail") or group.get("id", ""),
            "Owners": owner_str(group),
            "Created": (group.get("createdDateTime") or "")[:10],
            "Last Activity": "",
            "Max Severity": max_severity(findings),
            "Findings": "; ".join(f"[{s}] {d}" for s, d in findings),
            "Recommended Action": "Assign active owner or delete group",
        })

    for user, findings in user_results:
        if not findings:
            continue
        recommended = ""
        finding_texts = [d for _, d in findings]
        if any("license" in d for d in finding_texts):
            recommended = "Remove unneeded license(s) from disabled account"
        elif any("mailbox" in d for d in finding_texts):
            recommended = "Verify mailbox still needed; remove or convert to shared"
        elif any("no sign-in" in d for d in finding_texts):
            recommended = "Verify account still needed; disable or delete if stale"
        else:
            recommended = "Review account status"

        rows.append({
            "Type": "User Account",
            "Display Name": user.get("displayName", ""),
            "ID/Email": user.get("userPrincipalName", ""),
            "Owners": "",
            "Created": (user.get("createdDateTime") or "")[:10],
            "Last Activity": (user.get("signInActivity") or {}).get("lastSignInDateTime", "")[:10],
            "Max Severity": max_severity(findings),
            "Findings": "; ".join(f"[{s}] {d}" for s, d in findings),
            "Recommended Action": recommended,
        })

    for site, findings, usage in sp_results:
        if not findings:
            continue
        rows.append({
            "Type": "SharePoint Site",
            "Display Name": site.get("displayName") or site.get("name") or "",
            "ID/Email": site.get("webUrl") or "",
            "Owners": (usage or {}).get("owner_upn") or "",
            "Created": (site.get("createdDateTime") or "")[:10],
            "Last Activity": (usage or {}).get("last_activity") or "",
            "Max Severity": max_severity(findings),
            "Findings": "; ".join(f"[{s}] {d}" for s, d in findings),
            "Recommended Action": "Review site owner and activity; reassign or archive",
        })

    rows.sort(key=lambda r: (SEVERITY_ORDER.get(r["Max Severity"], 99), r["Display Name"].lower()))
    return rows


# ---------------------------------------------------------------------------
# Activity log
# ---------------------------------------------------------------------------

def append_activity_log(entry):
    with open(ACTIVITY_LOG, "a", encoding="utf-8") as f:
        f.write(entry + "\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    now = datetime.datetime.now()
    today_str = now.strftime("%Y-%m-%d")
    now_str = now.strftime("%Y-%m-%d %H:%M")

    try:
        env = load_env(ENV_PATH)
    except FileNotFoundError:
        print(f"ERROR: .env not found at {ENV_PATH}")
        sys.exit(1)

    tenant_id = env["TENANT_ID"]
    client_id = env["CLIENT_ID"]
    user_email = env["USER_EMAIL"]

    print(f"Authenticating admin account ({user_email})...")
    try:
        token = get_token(
            tenant_id, client_id, ADMIN_SCOPES,
            ADMIN_TOKEN_CACHE, login_hint=user_email,
        )
    except Exception as e:
        msg = f"Admin auth failed: {e}"
        print(f"ERROR: {msg}")
        append_activity_log(f"{now_str} - Orphaned asset scan - FAILED - {msg}")
        sys.exit(1)

    print("Authenticated. Fetching groups...")
    try:
        all_groups = fetch_groups(token)
        print(f"  {len(all_groups)} groups total")
    except RuntimeError as e:
        msg = str(e)
        print(f"ERROR: {msg}")
        append_activity_log(f"{now_str} - Orphaned asset scan - FAILED - {msg}")
        sys.exit(1)

    print("Fetching users...")
    try:
        all_users = fetch_users(token)
        signin_available = any("signInActivity" in u for u in all_users)
        print(f"  {len(all_users)} users")
        if not signin_available:
            print("  NOTE: signInActivity not present in user records — sign-in age checks will be limited")
    except RuntimeError as e:
        msg = str(e)
        print(f"ERROR: {msg}")
        append_activity_log(f"{now_str} - Orphaned asset scan - FAILED - {msg}")
        sys.exit(1)

    print("Fetching group activity report...")
    try:
        activity_map = fetch_group_activity_report(token)
        activity_available = activity_map is not None
    except RuntimeError as e:
        msg = str(e)
        print(f"ERROR: {msg}")
        append_activity_log(f"{now_str} - Orphaned asset scan - FAILED - {msg}")
        sys.exit(1)

    # Classify groups
    m365_groups = [g for g in all_groups if is_m365_group(g)]
    dl_groups = [g for g in all_groups if is_distribution_or_mail_security(g)]
    print(f"\n  M365 Groups/Teams: {len(m365_groups)}")
    print(f"  Distribution/mail-enabled security groups: {len(dl_groups)}")

    print(f"\nAnalyzing {len(m365_groups)} M365 groups / Teams...")
    m365_results = []
    for group in sorted(m365_groups, key=lambda g: g.get("displayName", "").lower()):
        findings = analyze_group(group, activity_map, now, token)
        m365_results.append((group, findings))

    print(f"Analyzing {len(dl_groups)} distribution / mail-enabled security groups...")
    dl_results = []
    for group in sorted(dl_groups, key=lambda g: g.get("displayName", "").lower()):
        findings = analyze_group(group, activity_map, now, token)
        dl_results.append((group, findings))

    print(f"Analyzing {len(all_users)} users...")
    active_user_upns = build_active_user_set(all_users)
    user_results = []
    for user in sorted(all_users, key=lambda u: u.get("userPrincipalName", "").lower()):
        findings = analyze_user(user, now)
        user_results.append((user, findings))

    # Planner: authenticate as app, fetch plans for flagged M365 groups only
    cert_thumbprint = env.get("CERT_THUMBPRINT", "")
    cert_pfx_path = env.get("CERT_PFX_PATH", "")
    group_plans = {}
    if cert_thumbprint and cert_pfx_path:
        print("Acquiring app token for Planner (Tasks.Read.All)...")
        try:
            app_token = get_app_token(tenant_id, client_id, cert_thumbprint, cert_pfx_path)
            flagged_group_ids = [g["id"] for g, f in m365_results if f]
            print(f"  Fetching Planner plans for {len(flagged_group_ids)} flagged groups...")
            plan_total = 0
            for group_id in flagged_group_ids:
                plans = fetch_planner_plans_for_group(app_token, group_id)
                if plans:
                    group_plans[group_id] = [p.get("title") or "(untitled)" for p in plans]
                    plan_total += len(plans)
            print(f"  {plan_total} Planner plan(s) found in flagged groups")
        except RuntimeError as e:
            msg = str(e)
            print(f"  WARNING: Planner scan skipped — {msg}")
    else:
        print("CERT_THUMBPRINT or CERT_PFX_PATH not set in .env — skipping Planner scan")

    print("Fetching SharePoint sites...")
    try:
        all_sites = fetch_sharepoint_sites(token)
        sp_available = True
    except RuntimeError as e:
        msg = str(e)
        print(f"ERROR: {msg}")
        append_activity_log(f"{now_str} - Orphaned asset scan - FAILED - {msg}")
        sys.exit(1)

    print("Fetching SharePoint site usage report...")
    try:
        sp_usage_map = fetch_sharepoint_usage_report(token)
    except RuntimeError as e:
        msg = str(e)
        print(f"ERROR: {msg}")
        append_activity_log(f"{now_str} - Orphaned asset scan - FAILED - {msg}")
        sys.exit(1)

    print(f"Analyzing {len(all_sites)} SharePoint sites...")
    sp_results = []
    for site in sorted(all_sites, key=lambda s: (s.get("displayName") or "").lower()):
        usage, findings = analyze_sharepoint_site(site, sp_usage_map, active_user_upns, now)
        sp_results.append((site, findings, usage))

    # Write outputs
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    md_path = REPORTS_DIR / f"{today_str}.md"
    csv_path = REPORTS_DIR / f"{today_str}.csv"

    md_content = build_markdown(
        m365_results, dl_results, user_results, sp_results,
        today_str, now_str, tenant_id,
        activity_available=activity_available,
        signin_available=signin_available,
        sp_available=sp_available,
        group_plans=group_plans,
    )
    md_path.write_text(md_content, encoding="utf-8")
    print(f"\nWrote: {md_path}")

    csv_rows = build_csv_rows(m365_results, dl_results, user_results, sp_results)
    fieldnames = [
        "Type", "Display Name", "ID/Email", "Owners", "Created",
        "Last Activity", "Max Severity", "Findings", "Recommended Action",
    ]
    with open(csv_path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(csv_rows)
    print(f"Wrote: {csv_path}")

    # sp_results is (site, findings, usage) triples; normalize to (obj, findings) for counting
    def iter_findings(*result_lists):
        for results in result_lists:
            for row in results:
                yield row[1]  # findings is always index 1

    high_count = sum(1 for f in iter_findings(m365_results, dl_results, user_results, sp_results) if any(s == HIGH for s, _ in f))
    medium_count = sum(1 for f in iter_findings(m365_results, dl_results, user_results, sp_results) if any(s == MEDIUM for s, _ in f))
    low_count = sum(1 for f in iter_findings(m365_results, dl_results, user_results, sp_results) if any(s == LOW for s, _ in f))
    total_flagged = sum(1 for f in iter_findings(m365_results, dl_results, user_results, sp_results) if f)

    outcome = (
        f"{total_flagged} assets flagged (High: {high_count}, Medium: {medium_count}, Low: {low_count})"
    )
    print(f"\n{outcome}")
    append_activity_log(
        f"{now_str} - Orphaned asset scan - {outcome}"
        f" - reports/orphaned-assets/{today_str}.md"
    )


if __name__ == "__main__":
    main()
