from __future__ import annotations

import json
import sys
from collections import Counter
from datetime import datetime
from pathlib import Path

from docx import Document


REQUIRED_FIELDS = {
    "control_id",
    "title",
    "generated_at",
    "generated_by",
    "status",
    "tool_results",
    "findings",
    "output_dir",
}


def _load_payload(result_path: Path) -> dict:
    if not result_path.exists():
        raise FileNotFoundError(f"result.json not found: {result_path}")
    payload = json.loads(result_path.read_text(encoding="utf-8"))
    missing = sorted(REQUIRED_FIELDS - payload.keys())
    if missing:
        raise ValueError(f"result.json missing required fields: {', '.join(missing)}")
    return payload


def _report_date(payload: dict) -> str:
    stamp = datetime.fromisoformat(payload["generated_at"])
    return stamp.date().isoformat()


def _docx_path(payload: dict, output_dir: Path) -> Path:
    return output_dir / f"{payload['control_id']}-{_report_date(payload)}.docx"


def _severity_counts(findings: list[dict]) -> str:
    counts = Counter(item.get("severity", "Unknown") for item in findings)
    order = ["Critical", "High", "Medium", "Low", "Unknown"]
    parts = [f"{name}: {counts[name]}" for name in order if counts.get(name)]
    return ", ".join(parts) if parts else "No findings"


def _add_tools_run(doc: Document, tool_results: list[dict]) -> None:
    doc.add_heading("Tools Run", level=1)
    for item in tool_results:
        doc.add_paragraph(item["tool_name"], style="List Bullet")


def _add_findings(doc: Document, findings: list[dict]) -> None:
    doc.add_heading("Detailed Findings", level=1)
    if not findings:
        doc.add_paragraph("No linked open findings were returned by the mapped automated checks.")
        return
    for finding in findings:
        doc.add_paragraph(
            f"{finding['finding_id']} | {finding['severity']} | {finding['finding_type']}",
            style="List Bullet",
        )
        doc.add_paragraph(f"Object: {finding.get('object_name', 'n/a')}")
        doc.add_paragraph(f"Recommended action: {finding.get('recommended_action', 'n/a')}")
        doc.add_paragraph(f"Current status: {finding.get('status', 'n/a')}")


def _executive_summary(payload: dict) -> str:
    status = payload["status"]
    findings = payload["findings"]
    if status == "manual_required":
        return (
            "No automated control check exists for this Secure SketCH control. "
            "Manual evidence is required, and no pass/warn compliance conclusion was established by automation."
        )
    if status == "pass":
        return (
            "The mapped automated checks completed successfully and returned no linked open findings "
            "for this control at the time of execution."
        )
    return (
        f"The mapped automated checks completed, and {len(findings)} linked open finding(s) remain "
        "associated with this control."
    )


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        raise SystemExit("Usage: render_control_check_docx.py <result.json>")

    result_path = Path(argv[1]).resolve()
    payload = _load_payload(result_path)
    output_dir = Path(payload["output_dir"]).resolve()
    if not output_dir.exists():
        raise FileNotFoundError(f"output_dir not found: {output_dir}")

    doc = Document()
    doc.add_heading(f"Secure SketCH Control Check {payload['control_id']}", level=0)
    doc.add_paragraph(f"Control title: {payload['title']}")
    doc.add_paragraph(f"Generated: {payload['generated_at']}")
    doc.add_paragraph(f"Generated by: {payload['generated_by']}")
    doc.add_paragraph(f"Status: {payload['status']}")

    doc.add_heading("Executive Summary", level=1)
    doc.add_paragraph(_executive_summary(payload))

    _add_tools_run(doc, payload["tool_results"])

    doc.add_heading("Findings Summary", level=1)
    doc.add_paragraph(_severity_counts(payload["findings"]))

    _add_findings(doc, payload["findings"])

    doc.add_heading("Evidence Record", level=1)
    doc.add_paragraph(f"Evidence ID: {payload.get('evidence_id', 'n/a')}")
    
    doc.add_heading("Artifact Locations", level=1)
    doc.add_paragraph(f"Output directory: {output_dir}")

    if payload.get("notes"):
        doc.add_heading("Operator Notes", level=1)
        doc.add_paragraph(payload["notes"])

    doc.save(_docx_path(payload, output_dir))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
